#!/usr/bin/env bash
set -euo pipefail
export LC_ALL=C

out_file="$1"
overlay_dir="${2%/}/firmware"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

generated="$tmp_dir/overlay_files.c"
table_file="$tmp_dir/table"
: > "$table_file"

command -v zstd >/dev/null 2>&1 || {
	echo "firmware_overlay: zstd is required" >&2
	exit 1
}
command -v python3 >/dev/null 2>&1 || {
	echo "firmware_overlay: python3 is required" >&2
	exit 1
}

mapfile -d '' bin_files < <(
	find "$overlay_dir" -maxdepth 1 -type f -name '*.bin' -print0 |
		sort -z
)

if (( ${#bin_files[@]} == 0 )); then
	echo "firmware_overlay: no .bin payloads found in $overlay_dir" >&2
	exit 1
fi

{
	echo '// Generated by convert_overlay.sh. Do not edit.'
	echo '#include <linux/stddef.h>'
	echo '#include "overlay_files.h"'
	echo
} > "$generated"

declare -A used_array_names=()
count=0

for bin in "${bin_files[@]}"; do
	base="$(basename "$bin")"
	safe_name="${base%.bin}"
	safe_name="$(printf '%s' "$safe_name" | sed 's/[^a-zA-Z0-9_]/_/g')"
	array_name="${safe_name}_data"

	if [[ -n "${used_array_names[$array_name]+set}" ]]; then
		echo "firmware_overlay: duplicate generated name: $array_name" >&2
		exit 1
	fi
	used_array_names["$array_name"]=1

	original_size="$(stat -c '%s' "$bin")"
	if (( original_size == 0 )); then
		echo "firmware_overlay: refusing empty payload: $bin" >&2
		exit 1
	fi

	compressed="$tmp_dir/$base.zst"
	zstd -22 -q -f "$bin" -o "$compressed"
	compressed_size="$(stat -c '%s' "$compressed")"

	python3 - "$compressed" "$array_name" >> "$generated" <<'PY'
from pathlib import Path
import sys

data = Path(sys.argv[1]).read_bytes()
name = sys.argv[2]

print(f"static const unsigned char {name}[] = {{")
for offset in range(0, len(data), 12):
    chunk = data[offset:offset + 12]
    print("\t" + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
print("};")
print()
PY

	printf '\t{ .name = "%s", .data = %s, .len = %s, .orig_size = %s },\n' \
		"$base" "$array_name" "$compressed_size" "$original_size" \
		>> "$table_file"
	count=$((count + 1))
done

{
	echo 'const struct overlay_file firmware_file_list[] = {'
	cat "$table_file"
	echo '};'
	echo
	printf 'const int firmware_file_list_count = %d;\n' "$count"
} >> "$generated"

mv -f "$generated" "$out_file"
echo "GEN     $out_file ($count firmware overlay(s))"
