#!/usr/bin/env bash
set -euo pipefail
export LC_ALL=C

out_file="$1"
modules_dir="$2"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

mapfile -d '' modules < <(
	find "$modules_dir" -maxdepth 1 -type f -name '*.ko.bin' -print0 |
		sort -z
)

{
	echo '// Generated by gen_overlay.sh. Do not edit.'
	echo '#include <linux/stddef.h>'
	echo '#include "overlay_files.h"'
	echo
} > "$out_file"

table_file="$tmp_dir/table"
: > "$table_file"
count=0

for module in "${modules[@]}"; do
	base="$(basename "$module")"
	name="${base%.ko.bin}"
	name="${name//-/_}"
	array_name="$(printf '%s' "$name" | sed 's/[^a-zA-Z0-9_]/_/g')_zstd"
	compressed="$tmp_dir/$base.zst"
	original_size="$(stat -c '%s' "$module")"

	zstd -22 -q -f "$module" -o "$compressed"

	python3 - "$compressed" "$array_name" >> "$out_file" <<'PY'
from pathlib import Path
import sys

data = Path(sys.argv[1]).read_bytes()
name = sys.argv[2]

print(f"static const unsigned char {name}[] = {{")
for offset in range(0, len(data), 12):
    chunk = data[offset:offset + 12]
    print("\t" + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
print("};")
print()
PY

	compressed_size="$(stat -c '%s' "$compressed")"
	printf '\t{ .name = "%s", .data = %s, .compressed_size = %s, .original_size = %s },\n' \
		"$name" "$array_name" "$compressed_size" "$original_size" >> "$table_file"
	count=$((count + 1))
done

{
	echo 'const struct module_overlay_file module_overlay_files[] = {'
	if (( count == 0 )); then
		echo $'\t{ .name = NULL, .data = NULL, .compressed_size = 0, .original_size = 0 },'
	else
		cat "$table_file"
	fi
	echo '};'
	echo
	printf 'const size_t module_overlay_file_count = %d;\n' "$count"
} >> "$out_file"

echo "GEN     $out_file ($count module overlay(s))"
