# SPDX-License-Identifier: GPL-2.0
# Ordinary encode/decode and the private page-delta implementation.
ccflags-y += -O3
obj-$(CONFIG_LZ4KD_COMPRESS) += lz4kd_encode.o
obj-$(CONFIG_LZ4KD_DECOMPRESS) += lz4kd_decode.o
obj-$(CONFIG_LZ4KD_DELTA) += lz4kd_delta.o
